#!/usr/bin/env bash
# Regression test for the GTK runtime hook shipped in the AppImage.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
patcher="$root/packaging/appimage/configure_gtk_runtime.sh"
custom_apprun="$root/packaging/appimage/AppRun"

fixture="$(mktemp -d "${TMPDIR:-/tmp}/lamha-gtk-hook-test.XXXXXX")"
trap 'rm -rf "$fixture"' EXIT

test -x "$custom_apprun"
if grep -q 'AppRun\.wrapped' "$custom_apprun"; then
  echo "custom AppRun exposes AppRun.wrapped" >&2
  exit 1
fi
grep -q 'exec "\$this_dir/usr/bin/lamha"' "$custom_apprun"
grep -q 'export PATH="\$this_dir/usr/bin:' "$custom_apprun"

appdir="$fixture/AppDir"
mkdir -p "$appdir/apprun-hooks" "$appdir/usr/bin" "$fixture/xkb/rules"
printf '#!/usr/bin/env bash\nexport GDK_BACKEND=x11 # generated by linuxdeploy\n' \
  > "$appdir/apprun-hooks/linuxdeploy-plugin-gtk.sh"
printf '#!/usr/bin/env bash\nthis_dir="$(readlink -f "$(dirname "$0")")"\nexec "$this_dir"/AppRun.wrapped "$@"\n' > "$appdir/AppRun"
printf 'pc\n' > "$fixture/xkb/evdev.real"
ln -s ../evdev.real "$fixture/xkb/rules/evdev"

XKB_CONFIG_ROOT="$fixture/xkb" "$patcher" "$appdir"

hook="$appdir/apprun-hooks/linuxdeploy-plugin-gtk.sh"
if grep -q '^export GDK_BACKEND=x11' "$hook"; then
  echo "GTK hook still forces X11" >&2
  exit 1
fi
grep -q 'export GDK_BACKEND=wayland' "$hook"
grep -q 'XKB_CONFIG_ROOT' "$hook"
test -f "$appdir/usr/share/X11/xkb/rules/evdev"
test ! -L "$appdir/usr/share/X11/xkb/rules/evdev"
if grep -q 'AppRun\.wrapped' "$appdir/AppRun"; then
  echo "AppRun still exposes AppRun.wrapped" >&2
  exit 1
fi
test ! -e "$appdir/AppRun.wrapped"
grep -q 'export PATH="\$this_dir/usr/bin:' "$appdir/AppRun"
grep -q 'exec "\$this_dir"/usr/bin/lamha' "$appdir/AppRun"

wayland_result="$(
  APPDIR="$appdir" XDG_SESSION_TYPE=wayland WAYLAND_DISPLAY=wayland-0 \
    GDK_BACKEND= bash -c 'source "$1"; printf "%s" "$GDK_BACKEND"' _ "$hook"
)"
test "$wayland_result" = wayland

x11_result="$(
  APPDIR="$appdir" XDG_SESSION_TYPE=x11 WAYLAND_DISPLAY= \
    GDK_BACKEND= bash -c 'source "$1"; printf "%s" "$GDK_BACKEND"' _ "$hook"
)"
test "$x11_result" = x11

override_result="$(
  APPDIR="$appdir" XDG_SESSION_TYPE=wayland WAYLAND_DISPLAY=wayland-0 \
    GDK_BACKEND=x11 bash -c 'source "$1"; printf "%s" "$GDK_BACKEND"' _ "$hook"
)"
test "$override_result" = x11

echo "AppImage GTK runtime hook regression test passed"
